[rpc_endpoints]
bsc_testnet = "${RPC_BSC_TESTNET}"
bsc_mainnet = "${RPC_BSC_MAINNET}"

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer_runs = 1000
via_ir = true
evm_version = 'cancun'
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./script/config" },
]

[profile.default.fuzz]
runs = 5 # change this for higher number of fuzz runs locally

[profile.ci.fuzz]
runs = 1000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
